data:
  # trainpath: '/mounts/Datasets4/GeoLifeCLEF2022'
  trainpath: '../../../Téléchargements/geolife_dataset'
  # testpath: '/dummy/path/to/test'
  batch_size: 32
  num_workers: 4
  valid_ratio: 0.2

optim:
  algo: SGD
  params:
    lr: 0.001

nepochs: 10
loss: "CrossEntropyLoss"

logging:
  wandb: 
   project: Geolife_deeplearning
   entity: sample_entity
  logdir: "logdir"  # Better to provide the fullpath, especially on the cluster
# model:
#   class: Linear
model:
  class: BiModel
  num_layers : 2
